/* Automatically generated by ../../tools/pmGenPmFeatures.py on Sat Sep 10 13:35:54 2011.  DO NOT EDIT. */
#define HAVE_PRINT
#define HAVE_CLASSES
#define HAVE_REPLICATION
#define HAVE_GENERATORS
#define HAVE_STRING_FORMAT
#define HAVE_CLOSURES
#define HAVE_ASSERT
#define HAVE_DEFAULTARGS
#define HAVE_DEL
#define HAVE_BACKTICK
#define HAVE_FLOAT
#define HAVE_GC
#undef HAVE_BYTEARRAY
#define HAVE_IMPORTS
#define HAVE_DEBUG_INFO

